workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always
      


stages:
  - "test"
  - "build"
  - "deploy"

run_unit_tests:
  stage: test
  before_script:
    - echo "We would like to run our unit tests"
  script: 
    - echo " these tests are running now ... "
  after_script:
    - echo "Cleaning up temporary files ..."




run_lint_tests:
  stage: test
  before_script:
    - echo "We would like to run our lint tests"
  script: 
    - echo " these tests are running now ... "
  after_script:
    - echo "Cleaning up temporary files ..."



build_image:
  only:
    - main
  stage: build
  script: 
    - echo "Building the docker image form our project ..."
    - echo "Tagging the docker image ..."

push_image:
  only:
    - main
  stage: build
  needs:
    - buid_image
  script:
    - echo "Logging to docker registrey ..."
    - echo "Pushing  to docker registrey ..."

deploy_image:
  only:
     - main
  stage: deploy
  script:
      - echo "Deploying the Docker image ..."



